services:
  - type: web
    name: telegram-forwarder
    env: python
    region: oregon
    plan: free
    
    # Python version set karo
    python:
      version: 3.12
    
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    
    envVars:
      - key: API_ID
        value: 30622410
      - key: API_HASH
        value: ac0e642a6cf43ced04f3cc2eabf5a21d
      - key: SOURCE_CHAT
        value: -1003801298314
      - key: DEST_CHAT
        value: -1003882932953
      - key: DELAY
        value: 1.5
      - key: PYTHON_VERSION
        value: 3.12
